### ISSUE TITLE
Does copykit account for the baseline copy number differences on the chrX and Y between male and female samples?

### ISSUE THREAD

**Issue by fangfang0906** [navinlabcode/copykit#103]
Thank you for developing copykit! I’m analyzing male samples and found a copy number loss on chromosome X. Could this reflect a true biological signal, or might it result from natural male X chromosome representation?

**Comment by darlanminussi** [comment]
Hi, if you sample is XY you will see only one copy of chromosome X. Relative to a normal diploid sample with two copies of each autosome, X will have one copy.
