### ISSUE TITLE
plotRatio() doesn't always let you plot a subset of bins

### ISSUE THREAD

**Issue by aislyn** [navinlabcode/copykit#61]
Not sure if this is just not fully implemented as a feature yet, or if it's a bug... 

The error seems to be an issue with the with the color function for plotting:
```
Error in `$<-.data.frame`(`*tmp*`, "colors", value = c("white", "gray",  : 
  replacement has 3 rows, data has 2
```

**Comment by darlanminussi** [comment]
Fixed in 69de005
Problem was with aesthetic. 
plotRatio(tumor[1:1000,], "cell")  works fine now.
