### ISSUE TITLE
row-based subsetting for all plot functions

### ISSUE THREAD

**Issue by aislyn** [navinlabcode/copykit#62]
It would be really helpful if all plot functions allowed scCNA objects that were subsetted by row to be plotted. 

e.g. `plotHeatmap(scCNA[1:1000,])`

In addition, it would be nice for plot functions to have an option to plot just a specific chromosome.

**Comment by darlanminussi** [comment]
This is currently possible. CopyKit objects support row-based subsetting and are compatible with plotting functions.
