### ISSUE TITLE
is there a way to get lists of CNVs

### ISSUE THREAD

**Issue by proukakis** [navinlabcode/copykit#87]
Hello we are greatly enjoying using this, having mostly used Ginkgo before. We do however need to come up with lists / text files of CNVs called, not just the plots / gene copy numbers. A vcf would be ideal, but obviously harder. I am sure that the data is in the code outputs, and perhaps it is our lack of expertise that is a problem. If there is a way to get the CNV regions as an output, it will be really helpful if you can explain how. Many thanks

**Comment by darlanminussi** [comment]
Hello, thank you for using CopyKit.

The bins within CopyKit and their genomic ranges can be obtained with the function `rowRanges(ck)`. This function, in combination with the accessors for the segment data `segment_ratios(ck)`, can be used to obtain the segment value for each bin.
This however is not yet a list of the copy number value for each segment, however it is possible to obtain data with a little bit of data wrangling and the function `rle()` applied to the sample-wise segment and matching to the indexes of the genomic ranges. I do realize that this is not trivial and perhaps writing a function to obtain these values in an easier way will be useful for a future version of CopyKit. 
From there, to obtain a list of CNVs can be done but it will depend a little bit on how the CNVs are defined and if you are working within the segment_ratios or the integer copy number space. Once you have that you can subset according to the CNV definition leaving you with a list of CNVs.
Sorry there isn't a more straightforward manner of obtaining directly a list for now, this is a good point that we will definitely consider making it easier.

**Comment by proukakis** [comment]
many thanks, we will try, but really look forward to this as a development, as it will make this a complete solution

**Comment by darlanminussi** [comment]
Thank you for the suggestion. We definitely will consider making this easier in future releases. Happy to help on how to do it in the meantime.

**Comment by proukakis** [comment]
thanks, will email you
