### ISSUE TITLE
germline gain not called in single cells

### ISSUE THREAD

**Issue by proukakis** [navinlabcode/copykit#88]
Hello we have as a positive control single cells with Picoplex WGA which carry a ~1.7 Mb germline triplication (total copy number 4). we are having trouble calling it at 220 kb bin size, even though the bins with high copy numbers are visible. We will look at smaller bin sizes, but I wonder if you would expect us to see something like this in a good quality cell? For what it's worth, Ginkgo gives the same results in the cells we compared. I can post output figures or send you files, but you are probably too busy, so no problem if you dont have any specific advice. thanks

**Comment by proukakis** [comment]
see attached- we tried to also run it without marking duplicates, in case this somehow caused the problems, but this didn't help. (I realise that cell L4 has an issue with chr9 and X alignments missing, we will recheck
<img width="1130" alt="Screenshot 2022-08-17 at 12 24 31" src="https://user-images.githubusercontent.com/18488392/185084495-1dd8d01d-64ad-46e0-a887-65655344235f.png">
)

**Comment by proukakis** [comment]
hi, sorry for delay (was on holiday). Alpha doesn't seem to help, thanks.
[fibroblasts_copykit  -  Read-Only.pptx](https://github.com/navinlabcode/copykit/files/9476549/fibroblasts_copykit.-.Read-Only.pptx)

**Comment by darlanminussi** [comment]
Related to control of alpha parameters for segmentation and merge levels.
Future version of copykit will reduce the sensitivity to avoid this problem
