### ISSUE TITLE
export IGV seg ratio file

### ISSUE THREAD

**Issue by MinBio** [navinlabcode/copykit#89]
It would be great if there is an easy way to export condense seg ratio file that can be import to IGV. cause some users are requesting this feature. Sincere thanks!

**Comment by darlanminussi** [comment]
That is a good idea, will see if it is possiblee

**Comment by pontushojer** [comment]
@darlanminussi This issue was closed as completed but I cannot find anything in the current documentation nor in the codebase. Is this feature added?
