### ISSUE TITLE
Install Instructions 

### ISSUE THREAD

**Issue by akcasasent** [navinlabcode/copykit#90]
Please add these to in install instructions: 

# Install Notes for CopyKit
​
Make sure you have Cario install on the OS level. Otherwise the plotHeatmaps will not work
​
## Macs 
You might need to install the following: 
​
1. Xcode - https://apps.apple.com/us/app/xcode/id497799835?mt=12
​
2. Macport - https://www.macports.org/install.php 
​
3. Xquartz - https://www.xquartz.org/
​
4. Cario - https://www.cairographics.org/download/
If you had to install Macports and Xcode please make sure to open a new terminal after these have been installed. 
​
    ```sudo port install cairo-devel```
    Note you will need the devel version not the just general cairo. 
    Suggest you - Restart computer.
    
5. In R: ```install.packages("Cairo", dependencies=TRUE)```
    

Fix for M1 chip MacBooks - Day 1- Installing Copykit, Signac:
Day 1- Installing Copykit, Signac:
These packages can be get-around and installed on M1 mac by using the R built for intel chips. I re-installed R-4.1.0.pkg (for intel chips); I previously had installed R-4.1.0.-arm64.pkg which is for the M1 chips. Johnny (the other guy who had similar problems) also successfully installed Copykit and Signac by using this version of R. The following resource has guided me: [https://support.bioconductor.org/p/9137290/](https://urldefense.com/v3/__https://support.bioconductor.org/p/9137290/__;!!BuQPrrmRaQ!kaowDVojd83uBrjNSYC5AkEXL2sopPUHn6nHnQ_Ocwer5EdjH-Gf1ZcOvPcFqT-w1vqKoOxqQvEMmGTdPplrEp8MIQ$)

## Windows
​
​

**Comment by darlanminussi** [comment]
added a FAQ section to the guide
