### ISSUE TITLE
RunSegmentation multipcf doesn't respect gamma parameter

### ISSUE THREAD

**Issue by seedgeorge** [navinlabcode/copykit#94]
Hi there,
While attempting to optimise the segmentation and clustering of my samples, I observed that tuning the 'gamma' parameter in `RunSegmentation` doesn't change anything - and from the code it doesn't seem to be connected up. It should be a simple fix in the call to multipcf, along these lines...

mpcf <- copynumber::multipcf(smooth_multipcf, 
            **gamma = gamma,**
            arms = vapply(regmatches(ref_chrarm$chrarm, 
            regexec("[pq]", ref_chrarm$chrarm)), FUN = "[", 1, 
            FUN.VALUE = character(1))
)

Related: in the function `knnSmooth`, perhaps being able to pass parameters to the internal segmentation call would be worthwhile?

**Comment by darlanminussi** [comment]
Thank you for pointing this out, I will try to fix it soon.

We try to keep functions isolated when possible. Hence, they do one thing well (also facilitate debugging issues), for this reason, for now, the adopted philosophy is to keep `knnSmooth` as a separate function and re-run `RunSegmentation` when needed prior to the smoothing step. A bit more cumbersome in terms of lines of code but it comes with benefits for the code and less confusion for the user.

**Comment by darlanminussi** [comment]
Hi, it is fixed in [5dff35f](https://github.com/navinlabcode/copykit/commit/5dff35fb0525e808cf1151e0c5bbb6a761e3aae9)

Thank you again for pointing that out.
