### ISSUE TITLE
mouse genome

### ISSUE THREAD

**Issue by LeonLiu-ZL** [navinlabcode/copykit#96]
I am from Dr. Viale's lab. I am trying to use the `copykit` to analyze mouse cell aneunploidy. For the `runVarbin()` function, the `genome` selections are `hg38` and `hg19`. Is there a way to analyze mouse cells. My bam files show the genome is `mm10`.

Also, from the bam file I got, I see some files with very good coverage and are labelled as "YesS", some files have low coverage and are labelled with "noS". Should I filter the bam files first and put the good coverage bam files for analysis? Or I can just put all the bam files in and `copykit` will decide which cells are good for analysis.

Thanks

**Comment by darlanminussi** [comment]
Hi, 

Sorry about the long time to get to this. Unfortunately, copykit does not have mm10 yet. It is possible however to use [custom scaffolds](https://navinlabcode.github.io/CopyKit-UserGuide/pre-processing.html#from-external-count-data-or-user-defined-scaffolds) if you have them available. You can try to contact some members of the Navin lab for help with that.

For the second question, CopyKit has filtering and qc functions to help you with keeping the cells with better quality in the analysis. See [here](https://navinlabcode.github.io/CopyKit-UserGuide/qc-module.html)

**Comment by Xiangjun99** [comment]
Hi @Puriney @darlanminussi  I would be very grateful for your help with this:

I am working with copyKit in the mouse genome (mm10) but am unsure how to build a custom mouse genome using custom scaffolds. Could you provide some guidance on this?

Thanks a lot for your help.
